[codestyle]
indent_type='space' # 'tab' or 'space'
indent_width=2
template_file='~/practice/atcoder/templates/templates.py'
workspace_dir='~/practice/atcoder/'
lang='python'

[etc]
download_without_login=true
parallel_download=false
save_no_session_cache=false
in_example_format="in_{}.txt"
out_example_format="out_{}.txt"

# C++は以下
# [codestyle]
# workspace_dir='~/practice/atcoder/'
# lang='cpp'
# indent_type='tab' # 'tab' or 'space'
# indent_width=2
# template_file='~/practice/atcoder/templates/templates.cpp'

# [compiler]
# compile_command='g++ main.cpp -o main -std=c++17'
# compile_only_when_diff_detected=true

# [tester]
# compile_before_testing=true
# compile_only_when_diff_detected=true
# timeout_adjustment=1.2

# [postprocess]
# exec_on_each_problem_dir='clang-format -i ./*.cpp'
# exec_on_contest_dir='touch CMakeLists.txt'
